// Copyright 2026 Lóránd Somogyi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSWindow {
  private var folders: DocumentFolders?
  private var badge: TimerBadge?

  override func awakeFromNib() {
    let flutterViewController = FlutterViewController()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    let folders = DocumentFolders()
    self.folders = folders
    FlutterMethodChannel(
      name: DocumentFolders.channelName,
      binaryMessenger: flutterViewController.engine.binaryMessenger
    ).setMethodCallHandler { call, result in folders.handle(call, result: result) }

    let badge = TimerBadge()
    self.badge = badge
    FlutterMethodChannel(
      name: TimerBadge.channelName,
      binaryMessenger: flutterViewController.engine.binaryMessenger
    ).setMethodCallHandler { call, result in badge.handle(call, result: result) }

    super.awakeFromNib()
  }
}

/// The macOS half of the running-timer badge: while a timer runs, the dock
/// shows the pre-rendered `AppIconRunning` variant (the app icon with the
/// recording dot, regenerated by tool/gen_app_icons.py); when it stops, nil
/// hands the dock the bundle's plain icon back.
///
/// A swapped image rather than `dockTile.badgeLabel`, because the label is
/// styled as the red unread-count bubble — a count is exactly what a running
/// timer is not.
final class TimerBadge: NSObject {
  static let channelName = "com.lorands.cirrhy/badge"

  func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    guard call.method == "setTimer" else {
      result(FlutterMethodNotImplemented)
      return
    }
    let arguments = call.arguments as? [String: Any] ?? [:]
    let running = arguments["running"] as? Bool ?? false
    NSApp.applicationIconImage = running ? NSImage(named: "AppIconRunning") : nil
    result(nil)
  }
}

/// The macOS half of the file-access port (DESIGN.md §4.1).
///
/// macOS belongs with iOS here rather than with the other two desktops, and
/// the reason is easy to miss: Flutter's macOS template ships with App Sandbox
/// enabled, so a picked folder's path keeps working for the life of the
/// process and fails after the first restart. The durable handle has to be a
/// **security-scoped bookmark**.
///
/// A near-copy of `ios/Runner/AppDelegate.swift` — see the note there on why
/// the two are not one shared file.
final class DocumentFolders: NSObject {
  static let channelName = "com.lorands.cirrhy/documents"

  /// Matches ChannelDocumentDirectory.unavailableCode on the Dart side.
  private static let unavailable = "unavailable"
  private static let failed = "failed"

  func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
    let arguments = call.arguments as? [String: Any] ?? [:]

    switch call.method {
    case "pickDirectory":
      pickDirectory(result: result)

    case "isAvailable":
      let handle = arguments["handle"] as? String
      offMainThread(result) { self.isAvailable(handle) }

    case "listDocuments":
      let handle = arguments["handle"] as? String
      let names = arguments["names"] as? [String] ?? []
      offMainThread(result) { try self.listDocuments(handle, names: names) }

    case "readDocument":
      let handle = arguments["handle"] as? String
      let name = arguments["name"] as? String
      offMainThread(result) { try self.readDocument(handle, name: name) }

    case "writeDocument":
      let handle = arguments["handle"] as? String
      let name = arguments["name"] as? String
      let bytes = arguments["bytes"] as? FlutterStandardTypedData
      offMainThread(result) { try self.writeDocument(handle, name: name, bytes: bytes?.data) }

    default:
      result(FlutterMethodNotImplemented)
    }
  }

  // MARK: - Picking

  private func pickDirectory(result: @escaping FlutterResult) {
    // A folder, not a document (§4.2): without the enclosing directory there
    // is nowhere to put the temp file that makes a save atomic.
    let panel = NSOpenPanel()
    panel.canChooseDirectories = true
    panel.canChooseFiles = false
    panel.allowsMultipleSelection = false
    panel.canCreateDirectories = true

    panel.begin { response in
      guard response == .OK, let url = panel.url else {
        result(nil)  // Cancelled.
        return
      }
      do {
        let bookmark = try url.bookmarkData(
          options: .withSecurityScope, includingResourceValuesForKeys: nil, relativeTo: nil)
        result([
          "handle": bookmark.base64EncodedString(),
          // The path, because on a desktop it is the most useful thing to
          // show and the one platform where it means something to the user.
          "label": url.path,
        ])
      } catch {
        result(
          FlutterError(code: Self.unavailable, message: error.localizedDescription, details: nil))
      }
    }
  }

  // MARK: - The folder

  /// Resolves the bookmark and runs [body] with the folder access open.
  ///
  /// A bookmark that resolves as stale is still used. Apple's advice is to
  /// rebuild it, which needs a way to hand the replacement back to Dart that
  /// the channel does not have yet; forcing the user to re-pick a folder that
  /// still works would be the worse of the two.
  private func withFolder<T>(_ handle: String?, _ body: (URL) throws -> T) throws -> T {
    guard let handle, let data = Data(base64Encoded: handle) else {
      throw Unavailable("the stored folder handle is unreadable")
    }

    var stale = false
    let url: URL
    do {
      url = try URL(
        resolvingBookmarkData: data, options: .withSecurityScope, relativeTo: nil,
        bookmarkDataIsStale: &stale)
    } catch {
      throw Unavailable(error.localizedDescription)
    }

    guard url.startAccessingSecurityScopedResource() else {
      throw Unavailable("access to that folder was withdrawn")
    }
    defer { url.stopAccessingSecurityScopedResource() }
    return try body(url)
  }

  private func isAvailable(_ handle: String?) -> Bool {
    (try? withFolder(handle) { url in
      var isDirectory: ObjCBool = false
      let exists = FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory)
      return exists && isDirectory.boolValue && FileManager.default.isWritableFile(atPath: url.path)
    }) ?? false
  }

  private func listDocuments(_ handle: String?, names: [String]) throws -> [String] {
    try withFolder(handle) { url in
      names.filter { FileManager.default.fileExists(atPath: url.appendingPathComponent($0).path) }
    }
  }

  private func readDocument(_ handle: String?, name: String?) throws -> FlutterStandardTypedData? {
    guard let name else { throw Unavailable("no document name") }
    return try withFolder(handle) { folder in
      let file = folder.appendingPathComponent(name)
      // Nothing there is the ordinary first run. A missing *folder* threw
      // above, because reading that as an empty document would write the
      // user's history away on the next save.
      guard FileManager.default.fileExists(atPath: file.path) else { return nil }

      var coordinationError: NSError?
      var data: Data?
      var readError: Error?
      // Coordinated, which is also what makes a provider materialise a file it
      // has only a placeholder for (§4.4).
      NSFileCoordinator().coordinate(readingItemAt: file, options: [], error: &coordinationError) {
        url in
        do { data = try Data(contentsOf: url) } catch { readError = error }
      }
      if let error = coordinationError ?? readError {
        throw Unavailable(error.localizedDescription)
      }
      return data.map { FlutterStandardTypedData(bytes: $0) }
    }
  }

  private func writeDocument(_ handle: String?, name: String?, bytes: Data?) throws {
    guard let name, let bytes else { throw Unavailable("nothing to write") }
    try withFolder(handle) { folder in
      let file = folder.appendingPathComponent(name)

      var coordinationError: NSError?
      var writeError: Error?
      NSFileCoordinator().coordinate(
        writingItemAt: file, options: .forReplacing, error: &coordinationError
      ) { url in
        // .atomic is temp-then-rename inside the same directory — KeePass's
        // file transaction (§4.3), and the reason directory scope was needed.
        do { try bytes.write(to: url, options: .atomic) } catch { writeError = error }
      }
      if let error = coordinationError ?? writeError {
        throw Unavailable(error.localizedDescription)
      }
    }
  }

  // MARK: - Plumbing

  private struct Unavailable: Error {
    let message: String
    init(_ message: String) { self.message = message }
  }

  /// Runs the work off the main thread and answers on it, because a
  /// FlutterResult may only be delivered from the platform thread.
  private func offMainThread(_ result: @escaping FlutterResult, _ work: @escaping () throws -> Any?)
  {
    DispatchQueue.global(qos: .userInitiated).async {
      do {
        let value = try work()
        // Void marks a void method (writeDocument); the standard codec
        // cannot encode the empty tuple, so answer nil.
        let reply = value is Void ? nil : value
        DispatchQueue.main.async { result(reply) }
      } catch let error as Unavailable {
        DispatchQueue.main.async {
          result(FlutterError(code: Self.unavailable, message: error.message, details: nil))
        }
      } catch {
        DispatchQueue.main.async {
          result(
            FlutterError(code: Self.failed, message: error.localizedDescription, details: nil))
        }
      }
    }
  }
}
