// Copyright 2026 Lóránd Somogyi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'dart:convert';
import 'dart:io';

import 'package:cirrhy_merge/cirrhy_merge.dart';
import 'package:test/test.dart';

/// docs/reporting/cirrhy.json is the example document the README points
/// reporting prompts at, generated by tool/gen_example_document.py. These
/// tests keep it honest: it must remain a document this engine accepts, in
/// the codec's canonical byte form — otherwise the "any agent can report on
/// this file" claim rests on an example the app itself would not produce.
void main() {
  final file = File('../../docs/reporting/cirrhy.json');
  final bytes = file.readAsBytesSync();
  const codec = JsonDocumentCodec();

  test('the example document decodes and is populated', () {
    final doc = codec.decode(bytes);
    expect(doc.clients, isNotEmpty);
    expect(doc.projects, isNotEmpty);
    expect(doc.tasks, isNotEmpty);
    expect(doc.entries.length, greaterThan(1000));
    expect(doc.tombstones, isNotEmpty);
    expect(doc.runningTimers, isEmpty, reason: 'a document at rest');
  });

  test('the example is in canonical form: decode → encode reproduces it', () {
    final reencoded = codec.encode(codec.decode(bytes));
    // The committed file carries a trailing newline for git's sake; the
    // codec's output does not.
    expect(utf8.decode(reencoded), utf8.decode(bytes).trimRight());
  });

  test('merging the example with itself changes nothing', () {
    final doc = codec.decode(bytes);
    expect(codec.encode(mergeDocuments(doc, doc)), codec.encode(doc));
  });
}
